### ISSUE TITLE
SDK error

### ISSUE THREAD

**Issue by sevstels** [NordicPlayground/pc-nrfjprog-js#16]
Dear Nordic
All our last SDKs in "example/dfu" have same error.

Code is not corect: 
 nrf_clock_lf_cfg_t clock_lf_cfg = NRF_CLOCK_LFCLKSRC;
Impossible  properly initialize structure by this idiotic method.

Because  nrf_clock_lf_cfg_t is structure and contain many variables,  NRF_CLOCK_LFCLKSRC - is single value;

Thank`s...

**Comment by bihanssen** [comment]
@sevstels, there is no reference to NRF_CLOCK_LFCLKSRC in this repo. Did you intend to post in a different repo?

**Comment by sevstels** [comment]
Oh... sorry
I resend it directly to Developer forum.
